name: openfold3-env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - python
  - setuptools
  - pip
  - openmm
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy
  - pandas
  - PyYAML
  - requests
  - scipy
  - tqdm
  - typing-extensions
  - wandb
  - modelcif
  - awscli
  - pytest
  - ml-collections
  - mkl
  - aria2
  - git
  - ruff>=0.5.0
  - biotite>=1.1.0
  - rdkit
  - mmseqs2
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.1
  - memory_profiler
  - func_timeout
  - boto3
  - pydantic
  - conda-forge::python-lmdb
  - conda-forge::ijson
  - pip:
      - mpi4py
      - deepspeed
      - dm-tree
      - pdbeccdutils
