# NOTE: this yaml is provided as a reference to display the full set of configurable options for OpenFold3.

# Most experiments do not require a runner.yml
# When a runner.yml is used, it is not required to specify all configuration settings.

# For typical usage, please refer to the example runner yamls in examples/example_runner_yamls/, 
# instead of using this full configuration file. 

#######################

# ExperimentSettings: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/entry_points/validator.py#L247
# Overall experiment settings 
experiment_settings:
  mode: predict [predict | train]
  output_dir: ./ 
  log_dir: null
  seeds:
    - 42
  num_seeds: null
  use_msa_server: true
  use_templates: true
  skip_existing: false

# PLTrainerArgs: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/entry_points/validator.py#L121
# Configuration settings for pytorch lightning
pl_trainer_args:  
  max_epochs: 1000
  accelerator: gpu
  precision: 32-true
  num_nodes: 1
  devices: 1
  profiler: null
  log_every_n_steps: 1
  enable_checkpointing: true
  enable_model_summary: false
  deepspeed_config_path: null
  distributed_timeout: PT30M
  mpi_plugin: false

# ModelUpdate: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/projects/of3_all_atom/project_entry.py#L28
# Custom model settings and presets
model_update:  
  presets:   # [train | predict | low_mem | pae_enabled]
    - predict
    - low_mem
    - pae_enabled
  custom: {}

# Checkpoint path: [default: $HOME/.openfold3/of3_ft3_v1.pt]
inference_ckpt_path: $HOME/.openfold3/of3_ft3_v1.pt

# Cache path: [default: $HOME/.openfold3/]
cache_path: $HOME/.openfold3

# DataModuleArgs: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/entry_points/validator.py#L110
data_module_args: 
  batch_size: 1  # Note: Not tested for batch sizes > 1 
  data_seed: 42
  num_workers: 10
  num_workers_validation: 4 # Change num workers for thread limited workflows
  epoch_len: 4

# DatasetConfigKwargs: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/projects/of3_all_atom/config/dataset_configs.py#L270
# Arguments for creating template and MSA features
dataset_config_kwargs: 
  ccd_file_path: null  # if null, uses CCD from Biotite
  # MSA Settings: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/projects/of3_all_atom/config/dataset_config_components.py#L32
  # Use this section to customize parsing of MSAs into features, more information in docs/source/precomputed_msa_how_to.md
  msa: 
    max_rows_paired: 8191
    max_rows: 16384
    subsample_with_bands: false
    min_chains_paired_partial: 2
    pairing_mask_keys:
      - shared_by_two
      - less_than_600
    moltypes:
      - 0
      - 1
    max_seq_counts:
      uniref90_hits: 10000
      uniprot_hits: 50000
      bfd_uniclust_hits: 10000000
      bfd_uniref_hits: 10000000
      cfdb_uniref30: 10000000
      mgnify_hits: 5000
      rfam_hits: 10000
      rnacentral_hits: 10000
      nt_hits: 10000
      concat_cfdb_uniref100_filtered: 10000000
      colabfold_main: 16384
      colabfold_paired: 8192
    msas_to_pair:
      - uniprot_hits
      - uniprot
    aln_order:
      - uniref90_hits
      - bfd_uniclust_hits
      - bfd_uniref_hits
      - cfdb_uniref30
      - mgnify_hits
      - rfam_hits
      - rnacentral_hits
      - nt_hits
      - concat_cfdb_uniref100_filtered
      - colabfold_main
    paired_msa_order:
      - colabfold_paired
  template:
    n_templates: 4
    take_top_k: true
    distogram:
      min_bin: 3.25
      max_bin: 50.75
      n_bins: 39

# OutputWriterSettings: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/entry_points/validator.py#L141
# Configure the output formats / content
output_writing_settings: 
  structure_format: cif  [cif | pdb]
  full_confidence_output_format: json [json | npz]
  write_features: false
  write_latent_outputs: false

# MSAComputationSettings: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/core/data/tools/colabfold_msa_server.py#L904
# Configure MSA server settings for colabfold 
msa_computation_settings: 
  msa_file_format: npz
  server_user_agent: openfold
  server_url: https://api.colabfold.com/
  save_mappings: true
  msa_output_directory: <tmp-dir>/of3_colabfold_msas/ 
  cleanup_msa_dir: true

# TemplatePreprocessorSettings: https://github.com/aqlaboratory/openfold-3/blob/main/openfold3/core/data/pipelines/preprocessing/template.py#L1459
# Configure template processing settings, more information in docs/source/template_how_to.md
template_preprocessor_settings: 
  mode: predict
  moltypes:
    - 0
  max_sequences_parse: 200
  max_seq_id: null
  min_align: null
  min_len: null
  max_release_date: null
  min_release_date_diff: null
  max_templates: 20
  fetch_missing_structures: true
  create_precache: false
  preparse_structures: false
  create_logs: false
  n_processes: 1
  chunksize: 1
  structure_directory: <tmp-dir>/of3_template_data/template_structures
  structure_file_format: cif
  output_directory: <tmp-dir>/of3_template_data
  precache_directory: null
  structure_array_directory: null
  cache_directory: <tmp-dir>/of3_template_data/template_cache
  log_directory: null
  ccd_file_path: null