name: openfold3-env
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - setuptools==59.5.0
  - pip
  - openmm=7.7
  - pdbfixer
  - pytorch-lightning
  - biopython
  - numpy=1
  - pandas
  - PyYAML==5.4.1
  - requests
  - scipy
  - tqdm==4.62.2
  - typing-extensions
  - wandb
  - modelcif==0.7
  - ml-collections
  - mkl=2022.1
  - biotite==1.1.0
  - rdkit==2024.09.4
  - mmseqs2==15.6f452
  - bioconda::hmmer
  - bioconda::hhsuite
  - bioconda::kalign2
  - pytorch::pytorch=2.4
  - pytorch::pytorch-cuda=12.1
  - memory_profiler==0.61.0
  - func_timeout
  - boto3
  - conda-forge::python-lmdb
  - conda-forge::ijson
  - pip:
      - mpi4py==3.1.5
      - deepspeed==0.14.5
      - dm-tree==0.1.6
      - git+https://github.com/NVIDIA/dllogger.git
      - flash-attn==2.6.0.post1
      - pdbeccdutils
 
