# Model name, currently only af3_all_atom supported 
model_name: af3_all_atom
# Can be found in
# of3/model_implementations/<model_name>/configs/reference_config.yml 
# only one preset allowed for now
presets: 
- initial_training 

# General run settings
seed: 42
data_seed: 1234

num_gpus: 1
batch_size: 1
num_workers: 16
epoch_len: 100
max_epochs: -1
output_dir: ../test_train_output
deepspeed_config_path: ./deepspeed_config.json
mpi_plugin: false
log_lr : true
compile : true

# Checkpoint settings
restart_checkpoint_path: last
checkpoint:
  every_n_epochs: 1
  auto_insert_metric_name: false
  save_last: true
  save_top_k: -1

# All fields here must match pl.Trainer kwargs
pl_trainer:
  num_nodes: 1
  precision: bf16
  max_epochs: 1
  log_every_n_steps: 25

# Include to use wandb logging 
wandb:
  id: some_id   # Remove if no id present 
  project: PROJECT_NAME 
  entity: YOUR_USERNAME
  group: GROUP_NAME
  experiment_name: EXPERIMENT_NAME

# This section makes updates to the entire config 
config_updates:
  model:
    settings:
      use_deepspeed_evo_attention: True
      blocks_per_checkpoint: 1
  dataset_config_template:
    config:
      token_budget: 197
      loss:
        min_resolution: 0.05
  extra_configs:
    loss_weight_modes: 
      default:
        bond: 0.1

dataset_paths:
  PDB-weighted:
    alignments_directory: /<PDB_PATH>/alignments/
    alignment_db_directory: /<PDB_PATH>/alignments_db/
    target_structures_directory: /<PDB_PATH>/mmcif/
    reference_molecule_directory: /<REFERENCE_PATH>/molecules 
    dataset_cache_file: <PDB_PATH>/data_cache 
    template_cache_directory: <PDB_PATH>/template_cache 
    template_structures_directory: /<PDB_PATH>/template_mmcif/
    ccd_file: /<PDB_PATH>/ccd_file
  short-monomer-distillation:
    alignments_directory: /<MONOMER_PATH>/alignments/
    alignment_db_directory: /<MONOMER_PATH>/alignments_db/
    target_structures_directory: /<MONOMER_PATH>/mmcif/
    reference_molecule_directory: /<REFERENCE_PATH>/molecules 
    dataset_cache_file: <MONOMER_PATH>/data_cache 
    template_cache_directory: <MONOMER_PATH>/template_cache 
    template_structures_directory: /<MONOMER_PATH>/template_mmcif/
    ccd_file: /<MONOMER_PATH>/ccd_file

dataset_configs:
  train:
    PDB-weighted:
      class: PDBWeightedDataset 
      weight: 0.5
      config:
        loss_weight_mode: default 
        token_budget: 384
        n_templates: 1
        crop_weights:
          contiguous: 0.2
          spatial: 0.4
          spatial_interface: 0.4
    short-monomer-distillation:
      class: MonomerDistillationDataset      
      weight: 0.2
      config:
        loss_weight_mode: self_distillation 
        token_budget: 384
        n_templates: 1
        crop_weights:
          contiguous: 0.2
          spatial: 0.4
          spatial_interface: 0.4