# To demonstrate expected fields for runner yaml, as expected by
# model_implementations/registry.py
# We will read the model preset from a separate field.
mode: train
project_type: af3_all_atom
presets:
  - train

seed: 42
data_seed: 1234

num_gpus: 4
batch_size: 1
num_workers: 16
epoch_len: 200
max_epochs: -1
output_dir: ../test_train_output
deepspeed_config_path: ./deepspeed_configs/ds_stage2_default_offload.json
log_lr : true
compile : false
mpi_plugin: false

pl_trainer:
  num_nodes: 1
  precision: bf16-mixed
  max_epochs: 1
  log_every_n_steps: 25

# Checkpoint settings
restart_checkpoint_path: last
checkpoint:
  every_n_epochs: 1
  auto_insert_metric_name: false
  save_last: true
  save_top_k: -1

config_update:
  model:
    architecture:
      loss_module:
        diffusion:
          chunk_size: 8

dataset_paths:
  weighted-pdb:
    alignments_directory: none
    alignment_array_directory:  /data/alignments/pdb_msas_v3_preparsed
    target_structures_directory: /data/af3_dataset_releases/af3_training_data_v7/preprocessed_pdb/cif_files
    target_structure_file_format: pkl
    alignment_db_directory: none
    dataset_cache_file: /data/af3_dataset_releases/af3_training_data_v7/training_cache_with_templates.json
    reference_molecule_directory: /data/af3_dataset_releases/af3_training_data_v7/preprocessed_pdb/reference_mols
    template_cache_directory: /data/af3_dataset_releases/af3_training_data_v7/template_cache
    template_structure_array_directory: /data/af3_dataset_releases/af3_training_data_v4/template_structure_arrays
    template_structures_directory: none
    template_file_format: cif
    ccd_file: none

  long-monomer-distillation:
    alignments_directory: none
    alignment_db_directory: none
    alignment_array_directory: /data/af3_dataset_releases/af3_lmd_data_v2/lmd_msas_v2_preparsed
    target_structures_directory: /data/af3_dataset_releases/af3_lmd_data_v2/structure_files
    target_structure_file_format: pkl
    dataset_cache_file: /data/af3_dataset_releases/af3_lmd_data_v2/training_cache_lmd_with_templates.json
    reference_molecule_directory: /data/af3_dataset_releases/af3_lmd_data_v2/reference_mols
    template_cache_directory: /data/af3_dataset_releases/af3_lmd_data_v2/template_cache
    template_structures_directory: none
    template_structure_array_directory: /data/af3_dataset_releases/af3_training_data_v4/template_structure_arrays
    template_file_format: cif
    ccd_file: none

  val-weighted-pdb:
    alignments_directory: none
    alignment_array_directory: /data/alignments/pdb_msas_v3_preparsed
    target_structures_directory: /data/af3_dataset_releases/af3_training_data_v6/preprocessed_pdb/cif_files
    target_structure_file_format: pkl
    alignment_db_directory: none
    dataset_cache_file: /data/af3_dataset_releases/af3_val_data_v2/val_cache_1536_with_templates_no_err.json
    reference_molecule_directory: /data/af3_dataset_releases/af3_training_data_v6/preprocessed_pdb/reference_mols
    template_cache_directory: /data/af3_dataset_releases/af3_val_data_v2/template_cache
    template_structure_array_directory: /data/af3_dataset_releases/af3_training_data_v4/template_structure_arrays
    template_structures_directory: none
    template_file_format: cif
    ccd_file: none

dataset_configs:
  train:
    weighted-pdb:
      class: WeightedPDBDataset
      weight: 0.5
      config:
        loss_weight_mode: default
        template:
          n_templates: 4
        custom:
          crop:
            token_budget: 384
            crop_weights:
              contiguous: 0.2
              spatial: 0.4
              spatial_interface: 0.4
    long-monomer-distillation:
      class: ProteinMonomerDataset
      weight: 0.5
      config:
        loss_weight_mode: default
        template:
          n_templates: 4
        custom:
          crop:
            token_budget: 384
            crop_weights:
              contiguous: 0.25
              spatial: 0.75
              spatial_interface: 0.0
  validation:
    val-weighted-pdb:
      class: ValidationPDBDataset
      config:
        template:
          n_templates: 4
