# To demonstrate expected fields for runner yaml, as expected by
# model_implementations/registry.py
# We will read the model preset from a separate field.
mode: eval
project_type: af3_all_atom
presets:
  - train

seed: 42
data_seed: 1234

log_level: debug

num_gpus: 4
batch_size: 1
num_workers: 4
epoch_len: 10
max_epochs: -1
output_dir: ../test_train_output
deepspeed_config_path: ./deepspeed_configs/ds_stage2_default_offload.json
log_lr : true
compile : false
mpi_plugin: false

pl_trainer:
  num_nodes: 1
  precision: bf16-mixed
  max_epochs: -1
  log_every_n_steps: 25

# wandb:
#   project: openfold3_debug 
#   entity: ayoumen
#   experiment_name: debug_dna_corr

# Checkpoint settings
restart_checkpoint_path: /global/cfs/cdirs/m4351/aqabel/61-23000.ckpt
checkpoint:
  every_n_epochs: 1
  auto_insert_metric_name: false
  save_last: true
  save_top_k: -1

config_update:
  model:
    architecture:
      loss_module:
        diffusion:
          chunk_size: 8

dataset_paths:
  weighted-pdb:
    alignments_directory: none # /pscratch/sd/v/vss2134/alignments/pdb_msas_completed
    alignment_db_directory: none
    alignment_array_directory: /global/cfs/cdirs/m4351/gnikol/data/pdb_msas_v3_preparsed/
    target_structure_file_format: pkl
    target_structures_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v8_proto/preprocessed_pdb/cif_files
    dataset_cache_file: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/training_cache_with_templates.json
    reference_molecule_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v8_proto/preprocessed_pdb/reference_mols
    template_cache_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/template_cache/
    template_structures_directory: none # /global/cfs/cdirs/m4351/ljarosch/of3_data/pdb_data/pdb_mmcif/mmcif_files
    template_structure_array_directory: /pscratch/sd/g/gnikol/data/template_preprocessing/template_structure_preprocessing_v4/template_structure_arrays
    template_file_format: cif
    ccd_file: /pscratch/sd/g/gnikol/data/template_preprocessing/components.cif

  val-weighted-pdb:
    alignments_directory: none
    alignment_array_directory: /global/cfs/cdirs/m4351/gnikol/data/pdb_msas_v3_preparsed/
    target_structures_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v8_proto/preprocessed_pdb/cif_files
    target_structure_file_format: pkl 
    alignment_db_directory: none
    dataset_cache_file: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v8_proto/validation_template_processing/validation_cache_with_templates.json
    reference_molecule_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v8_proto/preprocessed_pdb/reference_mols
    template_cache_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v8_proto/validation_template_processing/val_template_cache
    template_structure_array_directory: /pscratch/sd/g/gnikol/data/template_preprocessing/template_structure_preprocessing_v4/template_structure_arrays
    template_structures_directory: none
    template_file_format: "cif"
    ccd_file: none


dataset_configs:
  train:
    weighted-pdb:
      class: WeightedPDBDataset
      weight: 0.5
      config:
        loss_weight_mode: default
        template:
          n_templates: 4
          take_top_k: False
        custom:
          crop:
            token_budget: 384
            crop_weights:
              contiguous: 0.2
              spatial: 0.4
              spatial_interface: 0.4
  validation:
    val-weighted-pdb:
      class: ValidationPDBDataset
      config:
        template:
          n_templates: 4
          take_top_k: True
