# To demonstrate expected fields for runner yaml, as expected by
# model_implementations/registry.py 
# We will read the model preset from a separate field.
mode: train
project_type: af3_all_atom
presets: train 

mpi_plugin: false
seed: 42
checkpoint_every_epoch: false
batch_size: 1
num_gpus: 4
output_dir: ../test_train_output 
deepspeed_config_path: ./deepspeed_config.json
log_lr : false 

pl_trainer:
  num_nodes: 1
  precision: bf16-mixed
  max_epochs: 1
  log_every_n_steps: 25
  num_sanity_val_steps: 0 
  reload_dataloaders_every_n_epochs: 1 

config_update:
  model:
    architecture:
      input_embedder:
        linear_init_params:
          linear_s:
            init: relu
      pairformer:
        no_blocks: 4
  extra_configs:
    loss_weight_update:
      loss_weight_modes:
        default:
          bond: 1.0


dataset_paths:
  PDB-weighted:
    alignments_path: /<PDB_PATH>/alignments/
    alignment_index_path: /<PDB_PATH>/alignments/
    target_path: /<PDB_PATH>/mmcif/
    reference_molecule_directory: /<REFERENCE_PATH>/molecules 
    dataset_cache_path: <PDB_PATH>/data_cache 
    template_cache_path: <PDB_PATH>/template_cache 
    template_structures_path: /<PDB_PATH>/template_mmcif/
  short-monomer-distillation:
    alignments_path: /<MONOMER_PATH>/alignments/
    alignment_index_path: /<MONOMER_PATH>/alignments/
    target_path: /<MONOMER_PATH>/mmcif/
    reference_molecule_directory: /<REFERENCE_PATH>/molecules 
    dataset_cache_path: <MONOMER_PATH>/data_cache 
    template_cache_path: <MONOMER_PATH>/template_cache 
    template_structures_path: /<MONOMER_PATH>/template_mmcif/

dataset_configs:
  train:
    PDB-weighted:
      class: WeightedPDBDataset 
      weight: 0.5
      config:
        loss_weight_mode: default 
        token_budget: 384
        n_templates: 1
        crop_weights:
          contiguous: 0.2
          spatial: 0.4
          spatial_interface: 0.4
    short-monomer-distillation:
      class: ProteinMonomerDataset 
      weight: 0.2
      config:
        loss_weight_mode: self_distillation 
        token_budget: 384
        n_templates: 1
        crop_weights:
          contiguous: 0.2
          spatial: 0.4
          spatial_interface: 0.4