# To demonstrate expected fields for runner yaml, as expected by
# model_implementations/registry.py 
# We will read the model preset from a separate field.
mode: train
project_type: af3_all_atom
presets: 
  - train 

seed: 42
data_seed: 1215

num_gpus: 1
batch_size: 1
num_workers: 8
epoch_len: 50
max_epochs: -1
output_dir: /global/cfs/projectdirs/m4351/sk5059/OF3/debug/openfold3//test_train_output
deepspeed_config_path: deepspeed_configs/ds_stage2_default_offload.json
mpi_plugin: false
log_lr : false
compile : false

pl_trainer:
  num_nodes: 1
  precision: bf16-mixed
  max_epochs: 100
  log_every_n_steps: 25

config_update:
  model:
    architecture:
      loss_module: 
        diffusion:
          chunk_size: 16 
dataset_paths:
  weighted-pdb:
    alignments_directory: none # /pscratch/sd/v/vss2134/alignments/pdb_msas_completed
    alignment_db_directory: none
    alignment_array_directory: /global/cfs/cdirs/m4351/gnikol/data/pdb_msas_v3_preparsed/
    target_structure_file_format: pkl
    target_structures_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/preprocessed_pdb/cif_files
    dataset_cache_file: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/training_cache_with_templates.json
    reference_molecule_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/preprocessed_pdb/reference_mols
    template_cache_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/template_cache/
    template_structures_directory: none # /global/cfs/cdirs/m4351/ljarosch/of3_data/pdb_data/pdb_mmcif/mmcif_files
    template_structure_array_directory: /pscratch/sd/g/gnikol/data/template_preprocessing/template_structure_preprocessing_v4/template_structure_arrays
    template_file_format: cif
    ccd_file: /pscratch/sd/g/gnikol/data/template_preprocessing/components.cif
  long-monomer-distillation:
    alignments_directory: none
    alignment_db_directory: none
    alignment_array_directory: /global/cfs/cdirs/m4351/gnikol/data/lmd_msas_v2_preparsed # 
    target_structures_directory: /pscratch/sd/g/gnikol/data/af3_monomer_distillation_set/preprocessed_lmd_data/structure_files # 
    target_structure_file_format: pkl
    dataset_cache_file: /pscratch/sd/g/gnikol/data/template_preprocessing/template_alignment_preprocessing_v1_lmd/training_cache_lmd_with_templates.json #
    reference_molecule_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/preprocessed_pdb/reference_mols
    template_cache_directory: /pscratch/sd/g/gnikol/data/template_preprocessing/template_alignment_preprocessing_v1_lmd/template_cache #
    template_structures_directory: none
    template_structure_array_directory: /pscratch/sd/g/gnikol/data/template_preprocessing/template_structure_preprocessing_v4/template_structure_arrays #
    template_file_format: cif
    ccd_file: none 
  val-weighted-pdb:
    alignments_directory: none
    alignment_array_directory: /global/cfs/cdirs/m4351/gnikol/data/pdb_msas_v3_preparsed/
    target_structures_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/preprocessed_pdb/cif_files
    target_structure_file_format: pkl 
    alignment_db_directory: none
    dataset_cache_file: /pscratch/sd/j/jnwei22/template_cache/pdb_val_Dec27_with_templates.json
    reference_molecule_directory: /pscratch/sd/l/ljarosch/af3_dataset_releases/af3_training_data_v7/preprocessed_pdb/reference_mols
    template_cache_directory: /pscratch/sd/g/gnikol/data/template_preprocessing/template_alignment_preprocessing_v4_val/template_cache
    template_structure_array_directory: /pscratch/sd/g/gnikol/data/template_preprocessing/template_structure_preprocessing_v4/template_structure_arrays
    template_structures_directory: none
    template_file_format: "cif"
    ccd_file: none


dataset_configs:
  train:
    weighted-pdb:
      class: WeightedPDBDataset
      weight: 1
      config:
        n_templates: 4
        loss_weight_mode: default
        crop_weights:
          contiguous: 0.2
          spatial: 0.4
          spatial_interface: 0.4
  validation:
    val-weighted-pdb:
      class: ValidationPDBDataset
      config:
        n_templates: 4