experiment_settings:
  mode: train
  output_dir: ../test_train_output
  seed: 42
  restart_checkpoint_path: last

data_module_args:
  batch_size: 1
  data_seed: 1234
  num_workers: 16
  epoch_len: 4

pl_trainer_args:
  num_nodes: 1
  precision: bf16-mixed
  max_epochs: 2
  log_every_n_steps: 2
  deepspeed_config_path: ./deepspeed_configs/ds_stage2_default_offload.json

model_update:
  presets: 
    - train 
  custom:
    settings:
      ckpt_intermediate_steps: true

logging:
  log_lr: False
  wandb:
    id: some_id   # Remove if no id present 
    project: PROJECT_NAME 
    entity: YOUR_USERNAME
    group: GROUP_NAME
    experiment_name: EXPERIMENT_NAME
  
checkpoint:
  every_n_epochs: 1
  auto_insert_metric_name: false
  save_last: true
  save_top_k: -1

# This section specifies paths for training datasets
dataset_paths:
  weighted-pdb:
    alignments_directory: none 
    alignment_db_directory: none 
    alignment_array_directory: /<PDB_PATH>/alignments_db/
    dataset_cache_file: <PDB_PATH>/data_cache.json
    target_structures_directory: /<PDB_PATH>/targets_structures/
    target_structure_file_format: "npz"
    reference_molecule_directory: /<REFERENCE_PATH>/molecules 
    template_cache_directory: <PDB_PATH>/template_cache 
    template_structure_array_directory: /<PDB_PATH>/template_compressed/
    template_structures_directory: none
    template_file_format: "pkl"
    ccd_file: /<PDB_PATH>/ccd_file

  short-monomer-distillation:
    alignments_directory: none 
    alignment_db_directory: none 
    alignment_array_directory: /<MONOMER>/alignments_array/
    target_structures_directory: /<MONOMER_PATH>/target_structures/
    target_structure_file_format: "npz"
    reference_molecule_directory: /<REFERENCE_PATH>/molecules 
    dataset_cache_file: <MONOMER_PATH>/data_cache 
    template_cache_directory: <MONOMER_PATH>/template_cache 
    template_structures_directory: /<MONOMER_PATH>/template_mmcif/
    ccd_file: /<MONOMER_PATH>/ccd_file

dataset_configs:
  train:
    weighted_pdb:
      dataset_class: PDBWeightedDataset 
      weight: 0.5
      config:
        template:
          n_templates: 4
        crop:
          token_budget: 384
          crop_weights:
            contiguous: 0.2
            spatial: 0.4
            spatial_interface: 0.4

    short-monomer-distillation:
      dataset_class: ProteinMonomerDistillationDataset      
      weight: 0.2
      config:
        template:
          n_templates: 1
        crop:
          token_budget: 384
          crop_weights:
            contiguous: 0.2
            spatial: 0.4
            spatial_interface: 0.4