finetune1:
  loss:
    diffusion:
      bond_weight: 1.0
      smooth_lddt_weight: 0.0

finetune2:
  loss:
    diffusion:
      bond_weight: 1.0

finetune3:
  globals:
    diffusion_training_enabled: False
  model:
    heads:
      pae:
        enabled: True
      distogram:
        enabled: False
    loss:
      diffusion_weight: 0.0
      distogram_weight: 0.0
      confidence:
        pae:
          weight: 1.0

eval:
  globals:
    diffusion_training_enabled: False
    no_rollout_steps: 200