finetune1:
  loss_weight_update:
    loss_weight_mode:
      default:
        bond: 1.0
        smooth_lddt: 0.0

finetune2:
  model_update:
    loss_module:
      confidence:
        pde: 64
  dataset_update: # updates base dataset config
    cropping:
      crop_size: 768
  loss_weight_update: # updates base loss config
    loss_weight_mode:
      default:
        bond: 1.0

finetune3:
  model_update:
    settings:
      diffusion_training_enabled: False
    model:
      heads:
        pae:
          enabled: True
        distogram:
          enabled: False
  loss_weight_update:
    loss_weight_mode:
      default:
        diffusion_weight: 0.0
        distogram_weight: 0.0
        confidence:
          pae:
            weight: 1.0

eval:
  model_update:
    settings:
      diffusion_training_enabled: False
    model:
      shared:
        diffusion:
          no_rollout_steps: 200