train:
  settings:
    blocks_per_ckpt: 1
    ckpt_intermediate_steps: True
    chunk_size: null
    use_deepspeed_evo_attention: True

predict:
  settings:
    chunk_size: null
    use_deepspeed_evo_attention: True
    diffusion_training_enabled: False