finetune1:
  model:
    architecture:
      shared:
        diffusion:
          no_samples: 32
  dataset_config_template: 
    config:
      token_budget: 640
  extra_configs:
    loss_weight_modes:
      default:
        bond: 1.0
        smooth_lddt: 0.0

finetune2:
  model:
    architecture:
      shared:
        diffusion:
          no_samples: 32
  dataset_config_template: 
    config:
      token_budget: 768
  extra_configs: # updates base loss config
    loss_weight_modes:
      default:
        bond: 1.0

finetune3:
  model:
    settings:
      diffusion_training_enabled: False
    architecture:
      shared:
        diffusion:
          no_samples: 32
      heads:
        pae:
          enabled: True
        distogram:
          enabled: False
  extra_configs:
    loss_weight_modes:
      default:
        mse: 0.0
        smooth_lddt: 0.0
        distogram: 0.0
        pae: 1.0

eval:
  model:
    settings:
      diffusion_training_enabled: False
    architecture:
      shared:
        diffusion:
          no_rollout_steps: 200

train:
  model:
    settings:
      use_deepspeed_evo_attention: True
      blocks_per_ckpt: 1
      chunk_size: null
      use_block_sparse_attn: True