model_1:
  data:
    train:
      max_extra_msa: 5120
    predict: 
      max_extra_msa: 5120
    common:
      reduce_max_clusters_by_max_templates": true
      use_templates: true
      use_template_torsion_angles": true
  model:
    template:
      enabled: true

model_2:
  data:
    common:
      reduce_max_clusters_by_max_templates": true
      use_templates: true
      use_template_torsion_angles": true
  model:
    template:
      enabled: true

model_3:
  data:
    train:
      max_extra_msa: 5120
    predict: 
      max_extra_msa: 5120
  model:
    template:
      enabled: true

model_4:
  data:
    train:
      max_extra_msa: 5120
    predict: 
      max_extra_msa: 5120
  model:
    template:
      enabled: true

model_5:
  model:
    template:
      enabled: true

model_1_ptm:
  data:
    train:
      max_extra_msa: 5120
    predict: 
      max_extra_msa: 5120
    common:
      reduce_max_clusters_by_max_templates": true
      use_templates: true
      use_template_torsion_angles": true
  model:
    template:
      enabled: true
    heads:
      tm:
        enabled: true
  loss:
    tm:
      weight: 0.1

model_2_ptm:
  data:
    common:
      reduce_max_clusters_by_max_templates": true
      use_templates: true
      use_template_torsion_angles": true
  model:
    template:
      enabled: true
    heads:
      tm:
        enabled: true
  loss:
    tm:
      weight: 0.1

model_3_ptm:
  data:
    train:
      max_extra_msa: 5120
    predict: 
      max_extra_msa: 5120
  model:
    template:
      enabled: true
    heads:
      tm:
        enabled: true
  loss:
    tm:
      weight: 0.1

model_4_ptm:
  data:
    train:
      max_extra_msa: 5120
    predict: 
      max_extra_msa: 5120
  model:
    template:
      enabled: true
    heads:
      tm:
        enabled: true
  loss:
    tm:
      weight: 0.1

model_5_ptm:
  model:
    template:
      enabled: true
    heads:
      tm:
        enabled: true
  loss:
    tm:
      weight: 0.1

finetuning:
  data:
    train:
      crop_size: 384
      max_extra_msa: 5120
      max_msa_clusters: 512
  model:
    template:
      enabled: true 
  loss:
    violation:
      weight: 1.0
    experimentally_resolved:
      weight: 0.01

finetuning_no_templ:
  data:
    train:
      crop_size: 384
      max_extra_msa: 5120
      max_msa_clusters: 512
  model:
    template:
      enabled: false 
  loss:
    violation:
      weight: 1.0
    experimentally_resolved:
      weight: 0.01

finetuning_ptm:
  data:
    train:
      crop_size: 384
      max_extra_msa: 5120
      max_msa_clusters: 512
  model:
    template:
      enabled: true 
    heads:
      tm:
        enabled: true
  loss:
    violation:
      weight: 1.0
    experimentally_resolved:
      weight: 0.01
    tm:
      weight: 0.1

finetuning_no_templ_ptm:
  data:
    train:
      crop_size: 384
      max_extra_msa: 5120
      max_msa_clusters: 512
  model:
    template:
      enabled: false
    heads:
      tm:
        enabled: true
  loss:
    violation:
      weight: 1.0
    experimentally_resolved:
      weight: 0.01
    tm:
      weight: 0.1