train:
  settings:
    blocks_per_ckpt: 1
    ckpt_intermediate_steps: True

predict:
  settings:
    diffusion_training_enabled: False

low_mem:
  settings:
    memory:
      train:
        msa_module:
          swiglu_chunk_token_cutoff: null
          swiglu_seq_chunk_size: 4000
      eval:
        use_deepspeed_evo_attention: true
        chunk_size: 4
        msa_module:
          swiglu_chunk_token_cutoff: null
          swiglu_seq_chunk_size: null
        per_sample_token_cutoff: 750
        per_sample_atom_cutoff: 10000
        offload_inference:
          enabled: true
  architecture:
    loss_module: 
      diffusion:
        chunk_size: 4