train:
  settings:
    blocks_per_ckpt: 1
    ckpt_intermediate_steps: true
  architecture:
    loss_module:
      diffusion:
        chunk_size: 4

predict:
  settings:
    diffusion_training_enabled: False
    memory:
      eval:
        # This chunk size is the minimum value, it will be auto-tuned by default
        chunk_size: 4
  architecture:
    msa:
      msa_module_embedder:
        subsample_main_msa: False
        subsample_all_msa: True 
        
low_mem:
  settings:
    memory:
      eval:
        chunk_size: 4
        offload_inference:
          confidence_heads: true
          token_cutoff: None
