train:
  settings:
    blocks_per_ckpt: 1
    ckpt_intermediate_steps: true
  architecture:
    loss_module:
      diffusion:
        chunk_size: 4

predict:
  settings:
    diffusion_training_enabled: False
    memory:
      eval:
        # This chunk size is the minimum value, it will be auto-tuned by default
        chunk_size: 4
        msa_module:
          swiglu_chunk_token_cutoff: null
          swiglu_seq_chunk_size: null
        offload_inference:
          confidence_heads: true
          token_cutoff: 2800
  architecture:
    msa:
      msa_module_embedder:
        subsample_main_msa: False
        subsample_all_msa: True 
        
low_mem:
  settings:
    clear_cache_between_steps: True
    memory:
      eval:
        offload_inference:
          confidence_heads: true
          token_cutoff: 0
