name: Shapes tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ] 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install with conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

