name: Docker Image CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cleanup  # https://github.com/actions/virtual-environments/issues/2840
      run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Build the Docker image
      run: docker build -f Dockerfile -t openfold-docker .
    - name: Run import openfold 
      run: docker run openfold-docker python -c 'import openfold3' 
    - name: Run unit tests
      run: docker run openfold-docker pytest tests/ 