name: Build Official Openfold's docker image

on:
  workflow_dispatch:

jobs:
  cleanup:
    uses: ./.github/workflows/cleanup.yml

  build:
    runs-on: ubuntu-4core-150g-ssd 
    needs: cleanup

    steps:
    - uses: actions/checkout@v5
    - name: Cleanup  # https://github.com/actions/runner-images/issues/2840#issuecomment-2272410832
      shell: bash
      run: |
        echo "Clean up disk space before building docker image"
        df -h
        sudo rm -rf \
          "$AGENT_TOOLSDIRECTORY" \
          /opt/google/chrome \
          /opt/microsoft/msedge \
          /opt/microsoft/powershell \
          /opt/pipx \
          /usr/lib/mono \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/lib/node_modules \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift 
        df -h
    - name: Build the Docker image
      run: docker build -f Dockerfile -t openfold-docker .
      
    - name: Run sanity check 
      run: docker run openfold-docker python -c 'import openfold3'

    - name: Publishing image
      run: echo "TBD"