name: Build Official Openfold's docker image

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Clean up GH disk
      run: |
           sudo rm -rf $ANDROID_SDK_ROOT
           
    - uses: actions/checkout@v4
        
    - name: Build the Docker image
      run: docker build -f Dockerfile -t openfold-docker .
      
    - name: Run sanity check 
      run: docker run openfold-docker python -c 'import openfold3'

    - name: Publishing image
      run: echo "TBD"
      
