name: Build Official Openfold's docker image

on:
  workflow_dispatch:

jobs:
  cleanup:
    uses: ./.github/workflows/cleanup.yml

  build:
    runs-on: ubuntu-4core-150g-ssd 
    needs: cleanup

    steps:
    - uses: actions/checkout@v4
        
    - name: Build the Docker image
      run: docker build -f Dockerfile -t openfold-docker .
      
    - name: Run sanity check 
      run: docker run openfold-docker python -c 'import openfold3'

    - name: Publishing image
      run: echo "TBD"