name: Ruff

on: [push, pull_request]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Check for linter compliance
      - name: Lint with Ruff
        uses: chartboost/ruff-action@v1

      # Check for formatter compliance
      - name: Check formatting with Ruff
        if: always()
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
