name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  cleanup: 
    uses: ./.github/workflows/cleanup.yml

  build:
    runs-on: ubuntu-4core-150g-ssd 
    needs: cleanup 

    steps:
    - uses: actions/checkout@v4

    - name: Ensuring build paths
      run: mkdir -p resources/params

    - name: Cache Stereo Chemical Props
      id: cache-stereo_chemical_props
      uses: actions/cache@v4
      with:
        path: resources/stereo_chemical_props.txt
        key: shared-stereo_chemical_props-v1
        restore-keys: |
          shared-stereo_chemical_props-

    - name: Download Stereo Chemical Props
      if: steps.cache-stereo_chemical_props.outputs.cache-hit != 'true'
      run: |
           curl -sL -o resources/stereo_chemical_props.txt https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt

    - name: Cache Alphafold Params Model 1 PTM
      if: github.ref == 'refs/heads/inference-dev'
      id: cache-params_model_1_ptm
      uses: actions/cache@v4
      with:
        path: resources/params/params_model_1_ptm.npz
        key: shared-params_model_1_ptm-v1
        restore-keys: |
          shared-params_model_1_ptm-
        
    - name: Download Alphafold Params 2022-12-06
      if: steps.cache-params_model_1_ptm.outputs.cache-hit != 'true'
      run: |
           curl -sL -o resources/alphafold_params_2022-12-06.tar https://storage.googleapis.com/alphafold/alphafold_params_2022-12-06.tar
           tar -C resources/params -xvf resources/alphafold_params_2022-12-06.tar params_model_1_ptm.npz
           rm resources/alphafold_params_2022-12-06.tar

    - name: Building Docker images
      run: |
           docker build -f Dockerfile -t openfold-base . 
           docker build -f tests/Dockerfile -t openfold-test .
    
    - name: Run unit tests
      run: docker run -v ${{ github.workspace }}/resources:/opt/openfold3/openfold3/resources openfold-test:latest pytest tests