name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  cleanup: 
    uses: ./.github/workflows/cleanup.yml

  get-params:
    uses: ./.github/workflows/cache-params.yml
    needs: cleanup

  build:
    runs-on: ubuntu-4core-150g-ssd 
    needs: cleanup 

    steps:
    - uses: actions/checkout@v4

    - name: Building Docker images
      run: |
           docker build -f Dockerfile -t openfold-base . 
           docker build -f tests/Dockerfile -t openfold-test .

  test:
    runs-on: ubuntu-4core-150g-ssd 
    needs:
      - get-params
      - build

    steps:
    - uses: actions/checkout@v4

    - name: Run unit tests
      run: docker run -v ${{ github.workspace }}/resources:/opt/openfold3/openfold3/resources openfold-test:latest pytest tests
    
    - name: Run integration test 
      run: docker run -v ${{ github.workspace }}/resources:/opt/openfold3/openfold3/resources openfold-test:latest pytest tests/test_inference_full.py -m inference_verification